### ISSUE TITLE
Support controlling whether or not provenance/attestation information is included

### ISSUE THREAD

**Issue by PeterJCLaw** [bentoml/containerize-push-action#2]
Recent versions of BuildKit support (and maybe enable by default?) including provenance information in the images they generate. https://github.com/docker/build-push-action recently changed to enable this by default (in v4), however offers a mechanism to turn it off.

It would be great if this builder action also supported control over these properties. My main use-case is that I want to turn it off, though I appreciate others may want to keep it and/or have finer grained control.

**Comment by aarnphm** [comment]
yes we can support attestation since the buildx backend should already support this. I will work on this sometime later this week.

**Comment by PeterJCLaw** [comment]
For clarity: I believe that the images produced already include attestation -- I'd like to be able to turn it off.

**Comment by aarnphm** [comment]
Yes this should be synonymous to `build-push-action` attestation support.

**Comment by PeterJCLaw** [comment]
@aarnphm just wondering if there was any update on the timelines around this?
Having a quick look at the source, I'm guessing it's just a case of copying over the relevant parts from the `build-push-action` -- would it be useful if I put together a PR which did that?
